version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: $DOCKER_IMAGE_NAME
    container_name: $DOCKER_CONTAINER_NAME
    working_dir: /var/task
    volumes:
      - ./:/var/task
    ports:
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    env_file:
      - ./.env
